name: AnCasino
main: me.darazo.ancasino.AnCasino
authors: [Darazo, Auccuatt]
version: 1.1
api-version: 1.16
description: Real slot machines for your server.
softdepend: [Vault]
commands:
    casino:
        description: AnCasino
        usage: Incorrect command syntax. Check /<command> for command guide.
permissions:
    ancasino.*:
        description: Gives access to all AnCasino commands.
        default: op
        children:
            ancasino.admin: true
            ancasino.use: true
            ancasino.create: true
            ancasino.manage: true
    ancasino.admin:
        description: All AnCasino commands and permissions
        default: op
    ancasino.use:
        description: Allows you to use slot machines.
        default: false
    ancasino.create:
        description: User permissions for slot creation.
        default: false
    ancasino.manage:
        description: Permissions for managed slot machines.
        default: false